name: fluttertoast
description: Toast Library for Flutter, Easily create toast messages in single line of code
version: 7.1.8
homepage: https://github.com/PonnamKarthik/FlutterToast
issue_tracker: https://github.com/ponnamkarthik/FlutterToast/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.ponnamkarthik.toast.fluttertoast
        pluginClass: FlutterToastPlugin
      ios:
        pluginClass: FluttertoastPlugin
      web:
        pluginClass: FluttertoastWebPlugin
        fileName: fluttertoast_web.dart
  assets:
    - assets/
